# Copyright (c) Opendatalab. All rights reserved.
"""WMF/EMF 解析与渲染的固定安全预算。"""

from typing import Final


MAX_METAFILE_BYTES: Final = 128 * 1024 * 1024
MAX_RECORDS: Final = 1_000_000
MAX_POINTS_PER_RECORD: Final = 1_000_000
MAX_TOTAL_POINTS: Final = 5_000_000
MAX_COMMANDS: Final = 100_000
MAX_OBJECTS: Final = 65_536
MAX_STATE_DEPTH: Final = 64
MAX_DIAGNOSTICS: Final = 256
MAX_CANVAS_DIMENSION: Final = 8_192
MAX_CANVAS_PIXELS: Final = 16_000_000
MAX_RENDER_WORK_PIXELS: Final = 512_000_000
MAX_EMBEDDED_BITMAP_BYTES: Final = 128 * 1024 * 1024
MAX_FLATTENED_POINTS: Final = 5_000_000


__all__ = [
    "MAX_CANVAS_DIMENSION",
    "MAX_CANVAS_PIXELS",
    "MAX_COMMANDS",
    "MAX_DIAGNOSTICS",
    "MAX_EMBEDDED_BITMAP_BYTES",
    "MAX_FLATTENED_POINTS",
    "MAX_METAFILE_BYTES",
    "MAX_OBJECTS",
    "MAX_POINTS_PER_RECORD",
    "MAX_RECORDS",
    "MAX_RENDER_WORK_PIXELS",
    "MAX_STATE_DEPTH",
    "MAX_TOTAL_POINTS",
]
