lang:
  ch_server:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: ch_PP-OCRv6_medium_rec_infer.safetensors
    dict: ppocrv6_dict.txt
  ch:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: ch_PP-OCRv6_small_rec_infer.safetensors
    dict: ppocrv6_dict.txt
  korean:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: korean_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_korean_dict.txt
  ta:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: ta_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_ta_dict.txt
  te:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: te_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_te_dict.txt
  ka:
    det: Multilingual_PP-OCRv3_det_infer.pth
    rec: ka_PP-OCRv3_rec_infer.pth
    dict: ka_dict.txt
  arabic:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: arabic_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_arabic_dict.txt
  cyrillic:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: cyrillic_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_cyrillic_dict.txt
  devanagari:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: devanagari_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_devanagari_dict.txt
  east_slavic:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: eslav_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_eslav_dict.txt
  el:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: el_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_el_dict.txt
  th:
    det: ch_PP-OCRv6_small_det_infer.safetensors
    rec: th_PP-OCRv5_rec_infer.pth
    dict: ppocrv5_th_dict.txt
  seal:
    det: seal_PP-OCRv4_det_server_infer.pth
    rec: ch_PP-OCRv6_medium_rec_infer.safetensors
    dict: ppocrv6_dict.txt
  seal_lite:
    det: seal_PP-OCRv4_det_infer.pth
    rec: ch_PP-OCRv6_small_rec_infer.safetensors
    dict: ppocrv6_dict.txt
