from __future__ import annotations

import base64
from dataclasses import FrozenInstanceError
from io import BytesIO
from pathlib import Path

from PIL import Image, features
import pytest

from mineru.render._internal.docx.assets import (
    DocxAssetError,
    PreparedImage,
    prepare_block_image,
    prepare_html_image,
    prepare_image_bytes,
)
from mineru.types import ImageBodyBlock


def _image_bytes(image_format: str, *, size: tuple[int, int] = (7, 5)) -> bytes:
    """生成指定格式的有效测试图片字节。"""
    output = BytesIO()
    Image.new("RGBA" if image_format == "PNG" else "RGB", size, (20, 40, 60, 128)).save(
        output,
        format=image_format,
    )
    return output.getvalue()


def _data_uri(mime_subtype: str, payload: bytes) -> str:
    """把测试图片包装成严格 base64 data URI。"""
    encoded = base64.b64encode(payload).decode("ascii")
    return f"data:image/{mime_subtype};base64,{encoded}"


def _generated_svg(*, logical_size: tuple[int, int] = (7, 5), fallback_size: tuple[int, int] = (56, 40)) -> bytes:
    """构造带高密度 PNG fallback 的最小 MinerU SVG。"""
    fallback = base64.b64encode(_image_bytes("PNG", size=fallback_size)).decode("ascii")
    width, height = logical_size
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" data-metafile-render="wmf-emf">'
        f'<metadata id="metafile-render-raster-fallback" data-mime="image/png">{fallback}</metadata>'
        f'<path d="M 0 0 L {width} 0 L {width} {height} Z" fill="#000000"/>'
        "</svg>"
    ).encode()


def test_generated_svg_rejects_dtd_beyond_prefix_window() -> None:
    """验证 DOCX 不会嵌入在长前缀后隐藏 DTD 或实体声明的 SVG。"""
    payload = (
        b" " * 4097
        + b'<!DOCTYPE svg [<!ENTITY injected "expanded">]>'
        + _generated_svg().replace(b"</svg>", b'<text x="0" y="0" fill="#000">&injected;</text></svg>')
    )

    with pytest.raises(DocxAssetError, match="safely generated by MinerU"):
        prepare_image_bytes(payload, declared_extension="svg")


def _image_block(**values: str | None) -> ImageBodyBlock:
    """构造最小图片 body block。"""
    return ImageBodyBlock(type="image_body", index=0, content="", **values)


def test_block_prefers_sidecar_over_base64() -> None:
    """验证同时存在两种载荷时按公共契约优先解析 image_path。"""
    embedded_data = _image_bytes("PNG", size=(11, 9))
    sidecar_data = _image_bytes("PNG", size=(13, 7))

    def resolver(path: str) -> bytes:
        """验证 helper 请求规范 sidecar 路径并返回不同尺寸图片。"""
        assert path == "images/preferred.png"
        return sidecar_data

    prepared = prepare_block_image(
        _image_block(image_base64=_data_uri("png", embedded_data), image_path="images/preferred.png"),
        resolver,
    )

    assert prepared == PreparedImage(sidecar_data, "png", 13, 7)


def test_block_loads_safe_sidecar_through_resolver() -> None:
    """验证 sidecar 仅通过 resolver 读取，并返回真实格式和尺寸。"""
    jpeg_data = _image_bytes("JPEG", size=(13, 8))
    requested_paths: list[str] = []

    def resolver(path: str) -> bytes:
        """记录 renderer 交给调用方的规范化路径。"""
        requested_paths.append(path)
        return jpeg_data

    prepared = prepare_block_image(_image_block(image_path="images/photo.jpeg"), resolver)

    assert requested_paths == ["images/photo.jpeg"]
    assert prepared == PreparedImage(jpeg_data, "jpg", 13, 8)


def test_existing_cwd_file_is_never_read_without_resolver(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """验证即使 cwd 存在同名文件，helper 也不会自行读取。"""
    image_path = tmp_path / "images/local.png"
    image_path.parent.mkdir()
    image_path.write_bytes(_image_bytes("PNG"))
    monkeypatch.chdir(tmp_path)

    with pytest.raises(DocxAssetError, match="asset_resolver is required"):
        prepare_block_image(_image_block(image_path="images/local.png"))


def test_resolver_error_is_wrapped_with_safe_path() -> None:
    """验证 resolver 的底层异常被统一包装，并保留原始异常链。"""

    def failing_resolver(_path: str) -> bytes:
        """模拟调用方无法读取 sidecar。"""
        raise OSError("disk unavailable")

    with pytest.raises(DocxAssetError, match="images/missing.png") as error:
        prepare_html_image("images/missing.png", failing_resolver)

    assert isinstance(error.value.__cause__, OSError)


@pytest.mark.parametrize(
    "source",
    [
        "https://example.com/image.png",
        "http://example.com/image.png",
        "//example.com/image.png",
        "file:///tmp/image.png",
        "/tmp/image.png",
        "../image.png",
        r"C:\\image.png",
    ],
)
def test_html_image_rejects_remote_absolute_and_unsafe_sources(source: str) -> None:
    """验证 HTML 图片不会触发联网、绝对路径读取或目录逃逸。"""
    resolver_called = False

    def resolver(_path: str) -> bytes:
        """记录非法来源是否越过安全校验。"""
        nonlocal resolver_called
        resolver_called = True
        return _image_bytes("PNG")

    with pytest.raises(DocxAssetError):
        prepare_html_image(source, resolver)

    assert resolver_called is False


def test_html_data_uri_and_relative_sidecar_use_the_expected_source() -> None:
    """验证 HTML src 支持内联 data URI 以及由 resolver 提供的相对 sidecar。"""
    gif_data = _image_bytes("GIF", size=(6, 4))
    inline = prepare_html_image(_data_uri("gif", gif_data))
    sidecar = prepare_html_image("images/figure.gif", lambda path: gif_data if path == "images/figure.gif" else b"")

    assert inline == PreparedImage(gif_data, "gif", 6, 4)
    assert sidecar == inline


@pytest.mark.skipif(not features.check("webp"), reason="Pillow build does not support WebP")
def test_webp_is_converted_to_png_in_memory() -> None:
    """验证 WebP 会转为可嵌入 Word 的 PNG，且尺寸和像素保持有效。"""
    webp_data = _image_bytes("WEBP", size=(9, 7))
    prepared = prepare_html_image(_data_uri("webp", webp_data))

    assert prepared.extension == "png"
    assert prepared.data.startswith(b"\x89PNG\r\n\x1a\n")
    assert (prepared.width_px, prepared.height_px) == (9, 7)
    with Image.open(BytesIO(prepared.data)) as image:
        assert image.format == "PNG"
        assert image.size == (9, 7)


@pytest.mark.parametrize(
    ("image_format", "extension"),
    [
        ("PNG", "png"),
        ("JPEG", "jpg"),
        ("GIF", "gif"),
        ("TIFF", "tiff"),
        ("BMP", "bmp"),
    ],
)
def test_supported_word_image_formats_keep_original_bytes(image_format: str, extension: str) -> None:
    """验证 Word 可直接使用的五种格式不发生重编码。"""
    data = _image_bytes(image_format)

    prepared = prepare_image_bytes(data)

    assert prepared.data is data
    assert prepared.extension == extension
    assert (prepared.width_px, prepared.height_px) == (7, 5)


def test_svg_is_rejected_explicitly_for_data_uri_and_sidecar() -> None:
    """验证内联与 sidecar SVG 都返回明确的不支持错误。"""
    svg = b'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'

    with pytest.raises(DocxAssetError, match="SVG images are not supported"):
        prepare_html_image(_data_uri("svg+xml", svg))
    with pytest.raises(DocxAssetError, match="SVG images are not supported"):
        prepare_html_image("images/vector.svg", lambda _path: svg)


def test_mineru_generated_svg_keeps_native_data_and_high_density_png_fallback() -> None:
    """验证 DOCX 图片准备同时保留 SVG、逻辑尺寸与高密度 PNG。"""
    svg = _generated_svg()

    prepared = prepare_html_image(_data_uri("svg+xml", svg))

    assert prepared.svg_data == svg
    assert prepared.extension == "png"
    assert (prepared.width_px, prepared.height_px) == (7, 5)
    with Image.open(BytesIO(prepared.data)) as fallback:
        assert fallback.format == "PNG"
        assert fallback.size == (56, 40)


@pytest.mark.parametrize(
    "action",
    [
        lambda: prepare_html_image(_data_uri("jpeg", _image_bytes("PNG"))),
        lambda: prepare_html_image("data:image/png;base64,not-base64!"),
        lambda: prepare_image_bytes(b""),
        lambda: prepare_image_bytes(b"\x89PNG\r\n\x1a\ntruncated"),
        lambda: prepare_html_image("images/empty.png", lambda _path: b""),
        lambda: prepare_html_image("images/wrong.jpg", lambda _path: _image_bytes("PNG")),
    ],
)
def test_invalid_mime_empty_and_corrupt_payloads_are_rejected(action: object) -> None:
    """验证 MIME 不符、坏 base64、空字节、坏签名和扩展名不符都报错。"""
    with pytest.raises(DocxAssetError):
        action()  # type: ignore[operator]


def test_prepared_image_is_immutable() -> None:
    """验证 PreparedImage 是不可变的值对象。"""
    prepared = PreparedImage(b"image", "png", 1, 1)

    with pytest.raises(FrozenInstanceError):
        prepared.extension = "jpg"  # type: ignore[misc]
