name: Docker Base Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/china/Dockerfile --tag jianjungki/mineru_base:latest
      
   # 设置 Docker Hub 凭据
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 推送 Docker 镜像到 Docker Hub
    - name: Push Docker image for mineru_base
      run: docker push docker.io/jianjungki/mineru_base:latest
