name: Lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv python install 3.10
      - run: uv pip install ruff
      - run: uv run ruff check .
      - run: uv run ruff format --check .
