# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    tags:
      - '*released'
  workflow_dispatch:

permissions:
  contents: read


jobs:

  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Update version.py
        run: |
          python -m pip install packaging
          python update_version.py

      - name: Verify version.py
        run: |
          ls -l mineru/version.py
          cat mineru/version.py

      - name: Commit changes
        id: commit_changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add mineru/version.py
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
            echo "committed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "Update version.py with new version"
            echo "committed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Push changes
        if: steps.commit_changes.outputs.committed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git push origin HEAD:master

  check-install:
    needs: [ update-version ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: master
        fetch-depth: 0

    - name: Verify version.py
      run: |
        ls -l mineru/version.py
        cat mineru/version.py

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install mineru
      run: |
        python -m pip install --upgrade pip
        pip install -e .[core]

  build:
    needs: [ check-install ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10"]

    steps:

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: master
        fetch-depth: 0

    - name: Install build tools
      run: |
        python -m pip install wheel
        pip install build twine

    - name: Build wheel
      run: |
        python -m build --wheel

    - name: Check wheel metadata
      run: |
        python -m twine check --strict dist/*.whl

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: wheel-file
        path: dist/*.whl
        retention-days: 30

  publish:
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/mineru/
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: wheel-file
          path: dist

      - name: Create and Upload Release
        id: create_release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: './dist/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
